FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    make curl sudo vim unzip mysql-client

# golangのインストールのみ対話式になってしまうため別インストール
RUN apt-get install -y golang

WORKDIR /app
COPY go/ ./go
RUN go install -tags mysql github.com/golang-migrate/migrate/v4/cmd/migrate@v4.16.2
RUN cd ./go; go mod tidy

COPY ./docker/etc/bastion/script.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/script.sh

CMD ["/usr/local/bin/script.sh"]
