FROM node:20.4-alpine

WORKDIR /app/
COPY *.js *.ts *.json .env.local .prettierrc ./

RUN mkdir -p /app/public /app/src
COPY public/ /app/public/
COPY src/ /app/src/

RUN yarn install
RUN yarn build

ENTRYPOINT [ "yarn", "dev" ]
